-- AddForeignKey
ALTER TABLE "Fixture" ADD CONSTRAINT "Fixture_teamID1_fkey" FOREIGN KEY ("teamID1") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Fixture" ADD CONSTRAINT "Fixture_teamID2_fkey" FOREIGN KEY ("teamID2") REFERENCES "Team"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
